### ISSUE TITLE
Raster_to_geodataframe Plotting inconsistent Hex Resolution

### ISSUE THREAD

**Issue by butterisgod** [nmandery/h3ronpy#19]
I am encountering an issue with inconsistent hexagon resolution in the H3ron Uber H3 Raster library. Hexagons generated within the same image exhibit varying sizes, hindering accurate data analysis and interpretation.

I request your assistance in resolving this matter and achieving a uniform hex resolution throughout the image. Any guidance or support you can provide would be greatly appreciated. I am also willing to share examples or code snippets to aid in troubleshooting.
![Screenshot from 2023-05-23 03-49-16](https://github.com/nmandery/h3ronpy/assets/67658949/b569c635-87ec-47b1-97bf-c93488f3dbf7)

**Comment by nmandery** [comment]
Hi. You can prevent the mixed resolution cells by passing the additional keyword argument `compacted = False` to the function. The compaction is primarily intended to reduce memory requirements when converting large rasters.

**Comment by butterisgod** [comment]
Thank you sir. Your library has been very helpful. Thank you for your prompt response; this has saved me a lot of time.

**Comment by nmandery** [comment]
Glad to hear. 👍
