### ISSUE TITLE
Conversion from ndarray to h3 DataFrame throws unspecified error in h3ron.h3ron

### ISSUE THREAD

**Issue by vanyabrucker** [nmandery/h3ronpy#21]
Hi there!

Using raster.raster_to_dataframe throws an error in h3ronpy raster.py `RuntimeError: operation failed` at

```python
values, indexes = func(in_raster, _get_transform(transform), h3_resolution, axis_order, compacted, nodata_value)
``` 

The above line calls `raster.rs`'s `raster_to_h3 function`

the `raster_to_h3 function` instantiates the H3Converter class from `h3ron_ndarray` and there the `to_h3` function is called ([link to Github source](https://github.com/nmandery/h3ron/blob/main/h3ron-ndarray/src/array.rs#L246)).

The error thrown is defined in [h3ron.h3ron.src.error.rs](https://github.com/nmandery/h3ron/blob/main/h3ron/src/error.rs#L11C5-L11C5) and the `to_h3` function creates a HashMap type in `let mut h3_map = HashMap::default();` imported from h3ron.h3ron.src.collections.mod.rs, see [this line](https://github.com/nmandery/h3ron/blob/main/h3ron/src/collections/mod.rs#L37). 

But I don't know how the error is thrown or where I went off path. I am new to Rust and would be glad for pointers on how to resolve this :)

It does not happen with every GeoTIF, but crashes on Sentinel satellite data. I set up a Jupyter notebook for others to reproduce my error: https://github.com/vanyabrucker/h3ronpy-issue-21

Thanks!

**Comment by nmandery** [comment]
Good investigation and thank you for the notebooks :) . 

The error originates in the H3 library itself and returned as an error code, which is then converted into an [error type in h3ron](https://github.com/nmandery/h3ron/blob/7e2207c58dfe7c528c62a16c71fbad58b921600e/h3ron/src/error.rs#L86). The exact location is a bit hard to diagnose.

The cause for the error is the geotransform of the image fed into `raster_to_dataframe`. Looking at the notebook the CRS of the dataset is EPSG:32631. H3 uses WGS84/EPSG:4326. I ran your notebook (without the windowing) with an TIFF I reprojected manually using

```shell
gdalwarp -t_srs EPSG:4326 test_data/geotif/sample.tif test_data/geotif/sample.wgs84.tif
```
and it worked fine. It is also possible to reproject with `rasterio` on the fly, I just do not remember how without looking it up.

BTW: There is version 0.17 of `h3ronpy` now.

**Comment by vanyabrucker** [comment]
Thanks a lot @nmandery!

This resolved my issue.

I reprojected with `rasterio` using the following code:
```python
file_path = "test_data/geotif/sample.tif"
dataset = rasterio.open(file_path)
dataset_crs = dataset.crs

if dataset_crs != rasterio.crs.CRS.from_epsg(4326):
    print(f"Reprojecting raster from {dataset_crs} to EPSG:4326...")
   
    # Calculate transform array and shape of reprojected raster
    destination_crs = rasterio.crs.CRS.from_epsg(4326)
    transform, width, height = calculate_default_transform(dataset_crs, destination_crs, dataset.width, dataset.height, *dataset.bounds)

    # Working of the meta for the destination raster
    kwargs = dataset.meta.copy()
    kwargs.update({
        'crs': destination_crs,
        'transform': transform,
        'width': width,
        'height': height
    })

    # Open destination raster
    destination_raster = rasterio.open('test_data/geotif/test.tif', 'w', **kwargs)

    # Reproject and save raster band data
    for i in range(1, dataset.count + 1):
        reproject(
            source=rasterio.band(dataset, i),
            destination=rasterio.band(destination_raster, i),
            #src_transform=srcRst.transform,
            src_crs=dataset_crs,
            #dst_transform=transform,
            dst_crs=destination_crs,
            resampling=Resampling.nearest)

    # Close destination raster
    destination_raster.close()
else:
    print("Raster is already in EPSG:4326")
```

Also thanks for the upgrade to version 0.17 mention and your overall development efforts! The library is great :)

Do you think it would make sense to implement a more specific error? If you point me to the right place I will be happy to open a pull request. I need better comprehension of the library anyways and it will be good for my Rust skills too :D

**Comment by nmandery** [comment]
The ways to implement a more specific error in such cases are limited, as this library does not know anything about the CRS of the data. I pushed PR #22 to check at least if the extent of the data is out out the range of WGS84. 

Thanks for your offer to help - just submit a PR when your want to add something. I just added the check already as I was already adding some more docs ;)
