### ISSUE TITLE
Import failure on M1 MacBook Pro

### ISSUE THREAD

**Issue by diehl** [nmandery/h3ronpy#26]
Importing h3ronpy in a Jupyter notebook (version 7) is causing a kernel failure on my M1 MacBook Pro. I'm not totally surprised now that I'm no longer running my Python stack in emulation mode. I dropped down to a terminal and did the import at an iPython prompt and got the following message:
```
zsh: illegal hardware instruction  ipython
```
The import is working without issue on my Intel-based iMac so I'll proceed there, but wanted to share this.

**Comment by nmandery** [comment]
Thank you for reporting this. To resolve issues like this is the intention of #23. So far only wheels for x86 are build. I also need to investigate how to build for apple silicon using GitHub actions.

**Comment by diehl** [comment]
My pleasure @nmandery - I appreciate the quick follow up!

**Comment by nmandery** [comment]
I just released v0.17.5 to PyPI including a amd64 wheel for mac. I was unable to test this on apple silicon, but hopefully it should work.

It would be appreciated if you could test this

**Comment by diehl** [comment]
@nmandery The import works just fine now on my end! Appreciate the update!

**Comment by nmandery** [comment]
Thank you for testing.

**Comment by diehl** [comment]
My pleasure!
