### ISSUE TITLE
Question: Best way to convert Polars series of Lat/Lng to H3 cells

### ISSUE THREAD

**Issue by mschrader15** [nmandery/h3ronpy#28]
Hi @nmandery, I have a large polars Dataframe with a struct column of WGS84 latitude and longitude. I want to map the Points to corresponding H3 cells.

Naturally using the uber h3 python library with `pl.struct(['lat', 'lng']).apply()` is quite slow. I found your library, but it looks like its only made to work with geo-type data. Is there a workaround outside of polars -> geopandas -> polars?

**Comment by nmandery** [comment]
A dedicated function create cells from separate x, y and resolutions series is something I forgot to implement. I am tagging this issue as feature request to add this in the future.

While it is far from optimal as it requires a string allocation and some parsing, you can try to work around this using the `cells_parse` function:

```python
import polars as pl
from h3ronpy.polars import cells_parse

df = pl.DataFrame({
    "x": pl.Series([10.0, 35.5]),
    "y": pl.Series([-3.0, -12.5]),
    "res": pl.Series([4, 8]),
})
strings_df = df.select([
        pl.format("{};{};{}", pl.col("x"), pl.col("y"), pl.col("res")).alias("s"),
])
print(strings_df)
print(cells_parse(strings_df["s"]))
```

Not sure how fast this is, though.

**Comment by mschrader15** [comment]
Thanks for the quick reply! I took a brief stab at implementing a [x,y vector function in my fork](https://github.com/mschrader15/h3ronpy/blob/b1f7486028bb1e755959e5cdf015ccd29555dad7/src/vector.rs#L258-L286). Its not PR ready as I bypassed some of the h3ron & h3arrow abstractions for quick and dirty test.

See the results below:

```Python

import h3.api.numpy_int as h3
from h3ronpy.polars import cells_parse
from h3ronpy.polars.vector import latlng_to_cells

...

@timeit
def h3_cell_naive(test_df) -> pl.Series:
    return test_df.with_columns(
        [
            pl.struct(["lat", "lon"])
            .apply(lambda x: h3.latlng_to_cell(x["lat"], x["lon"], res))
            .alias("h3")
        ]
    )["h3"]


@timeit
def h3_cells_parse(test_df) -> pl.Series:
    return cells_parse(
        test_df.with_columns(
            pl.format("{};{};{}", pl.col("lon"), pl.col("lat"), pl.lit(res)).alias("s")
        )["s"]
    ).alias("h3_2")


@timeit
def h3_cells_vectorized(test_df) -> pl.Series:
    return test_df.with_columns(
        pl.struct(["lat", "lon"]).map(lambda x: latlng_to_cells(x.to_arrow(), res)).alias('h3')
    )


print(f"Rows: {test_df.shape[0]}")

h3_cell_naive(test_df)
h3_cells_parse(test_df)
h3_cells_vectorized(test_df)

-------------------------------
Rows: 10_000_000
Function h3_cell_naive Took 32.3439 seconds
Function h3_cells_parse Took 11.2510 seconds
Function h3_cells_vectorized Took 6.2865 seconds
```

**Comment by nmandery** [comment]
Nice :+1:  Seems we did the same thing at the same time :laughing:

**Comment by nmandery** [comment]
I will try to publish a new release within the next few days. Thanks for bringing this up.
