### ISSUE TITLE
ArrowIndexError: Negative buffer slice length

### ISSUE THREAD

**Issue by diehl** [nmandery/h3ronpy#40]
I executed the following command on a dataset I'm working with and saw the following error. Could anyone provide some guidance on what might be the issue here? Any pointers would be greatly appreciated!

```
ga_cells_df = geodataframe_to_cells(ga_gdf, 10)
```

```
---------------------------------------------------------------------------
ArrowIndexError                           Traceback (most recent call last)
File <timed exec>:1

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/h3ronpy/pandas/vector.py:124, in geodataframe_to_cells(gdf, resolution, containment_mode, compact, cell_column_name, all_intersecting)
    116 cells = _av.wkb_to_cells(
    117     gdf.geometry.to_wkb(),
    118     resolution,
   (...)
    121     all_intersecting=all_intersecting,
    122 )
    123 table = pa.Table.from_pandas(pd.DataFrame(gdf.drop(columns="geometry"))).append_column(cell_column_name, cells)
--> 124 return _arrow_util.explode_table_include_null(table, cell_column_name).to_pandas().reset_index(drop=True)

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/h3ronpy/arrow/util.py:10, in explode_table_include_null(table, column)
      8 other_columns.remove(column)
      9 indices = pc.list_parent_indices(pc.fill_null(table[column], [None]))
---> 10 result = table.select(other_columns).take(indices)
     11 result = result.append_column(
     12     pa.field(column, table.schema.field(column).type.value_type),
     13     pc.list_flatten(pc.fill_null(table[column], [None])),
     14 )
     15 return result

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/pyarrow/table.pxi:2005, in pyarrow.lib._Tabular.take()

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/pyarrow/compute.py:486, in take(data, indices, boundscheck, memory_pool)
    446 """
    447 Select values (or records) from array- or table-like data given integer
    448 selection indices.
   (...)
    483 ]
    484 """
    485 options = TakeOptions(boundscheck=boundscheck)
--> 486 return call_function('take', [data, indices], options, memory_pool)

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/pyarrow/_compute.pyx:590, in pyarrow._compute.call_function()

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/pyarrow/_compute.pyx:385, in pyarrow._compute.Function.call()

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()

File ~/opt/miniconda3/envs/viz-prototyping/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()

ArrowIndexError: Negative buffer slice length
```

**Comment by nmandery** [comment]
I will look into this. 

Are there any NULLs or empty geometries in the dataframe you are using?

**Comment by diehl** [comment]
Thank you @nmandery - I'm not seeing any NaNs or empty geometries in the dataset.

**Comment by nmandery** [comment]
So far I have been unable to reproduce this error. Could you provide a test-dataset which triggers this error? Maybe a small subset of your dataframe is sufficient.

What version of pyarrow are you using?

**Comment by diehl** [comment]
Here's a link to the exact dataset I'm using: https://web.tresorit.com/l/J3zSS#XkNiAArLbMRKOWoCaL1XpA

The PyArrow version installed in my virtual environment is 14.0.1.

**Comment by nmandery** [comment]
Thanks, I now can reproduce it.

Fixing this will take some time I guess. The error originates in [this check](https://github.com/apache/arrow/blob/main/cpp/src/arrow/buffer.cc#L52) calling [this](https://github.com/apache/arrow/blob/26149d9fab0360e6d4d9a295f934100470c4bc37/cpp/src/arrow/util/slice_util_internal.h#L31). Not sure how this could be triggered without a bug in pyarrow.

**Comment by diehl** [comment]
That's great news @nmandery - no worries on the timing. I can explore other pathways in the meantime. Just glad I could contribute something here that will help make the library better.

**Comment by nmandery** [comment]
Hmm. Maybe it is memory related. I am using https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.select which creates a new table. When I am processing your dataset in batches of max. 10000 rows it works. When computing all of it at once, the error occurs and my 32Gb machine does not have much RAM left. If that is the reason, the error message is quite bad ;) At least you can work around the problem using batches. I will look into how to make the process less memory intensive.

**Comment by diehl** [comment]
I wouldn't be surprised. I'm breaking things left and right over here. ;-)

I've been experimenting a bit with `h3pandas` as well and I'm able to get to the stage where I've got a GeoDataframe with the cell geometries. When I do a GeoPandas `dissolve` operation to group cells into larger geometries, memory usage seems to grow without bound and crash my machine. All this to say that it seems challenging to integrate multiple attribute layers at high resolution and national scale.

**Comment by diehl** [comment]
@nmandery No worries Nico. I appreciate your prompt investigation of the issue and your suggestions about how to proceed. Thank you!
