### ISSUE TITLE
h3 library version 3.7, is there a plan to update for version 4.0?

### ISSUE THREAD

**Issue by luizamfsantos** [nmandery/h3ronpy#47]

**Comment by nmandery** [comment]
The only dependency to the h3 library is that it is used as a dependency in the tests. Internally h3ronpy uses a rust implementation of the h3 grid named h3o. So it is not really bound to releases of the h3 python library.

I just checked an it seems that the latest version of the h3 python library is still 3.7, version 4 is not stable yet.
