### ISSUE TITLE
local ij - methods request

### ISSUE THREAD

**Issue by sup3rcow** [nmandery/h3ronpy#49]
Hi,

I need to find exact neighbor position, and we can do it with local ij methods.

In h3-py, there are methods
experimental_h3_to_local_ij
experimental_local_ij_to_h3

(source code: https://github.com/uber/h3-py/blob/v3/src/h3/_cy/cells.pyx)

It would be nice if we can have those methods also ih h3ronpy.

**Comment by nmandery** [comment]
Hi, thanks for the input. I will look into adding this the next time I am working on this.
