### ISSUE TITLE
Nans no indexed even when nodata_value is set to a numerical value

### ISSUE THREAD

**Issue by jorge-cervest** [nmandery/h3ronpy#5]
Hi, 

I have a raster where a large area is represented by nan values. However, nans have a meaning (as in is not possible to get a result in that area) so I would like to index them. 

When using `raster_to_dataframe`, regardless of the value I give to `nodata_value`, nans are not indexed.

Is there anything I can do to be able to index nan areas?

Thanks
Jorge

**Comment by nmandery** [comment]
Hi Jorge,

There is no explicit filtering out if NaNs, but NaNs are sometimes require a bit special handling. I will have a look why this behaviour you observed is happening.

**Comment by nmandery** [comment]
I just tried to reproduce the issue you encountered and was not able to run into the same problem. See the unittests I added in the commit above. I stumbled over the missing pandas `dropna=False` parameter first, though. Pandas seems to drop the NaNs in the default configuration of `value_counts`.

Could you please try to run these tests to see if they produce a different result?

**Comment by jorge-cervest** [comment]
Yeah I realised there was an issue with the raster. Your tests were great thanks!
