### ISSUE TITLE
Update for latest geoarrow

### ISSUE THREAD

**Issue by kylebarron** [nmandery/h3ronpy#56]
I'd love to update h3arrow for the latest geoarrow-rs, and potentially use `h3arrow` as an (optional) dependency from [Lonboard](https://github.com/developmentseed/lonboard), a Python library for large geospatial vector data visualization.

Some changes:

- As of this week (unreleased) geoarrow-rs does not have an `O: OffsetSizeTrait` generic on the `PolygonArray`: https://github.com/geoarrow/geoarrow-rs/pull/803. In order to overflow the offsets of an `int32`, you'd need to have more than `2^32` coordinates in a single contiguous array, which would take up 32GB alone. Removing this generic makes it easier to move faster in geoarrow-rs and took out a ton of complexity.
- On the contrary, I think supporting multiple dimensions in geoarrow-rs _is_ necessary complexity. So arrays now have a `const D: usize` generic for the physical dimension. So now when you construct arrays you'd have `PolygonArray<2>`.
- I started to implement a [`pyo3-geoarrow` Rust helper module](https://github.com/geoarrow/geoarrow-rs/tree/main/python/pyo3-geoarrow) to make it easier to handle zero-copy data interop from Python, but that's not yet fully standardized.

Let me know if I can help or give pointers to any of this.

**Comment by nmandery** [comment]
Great. I did not know about lonboard - looks good. Do you want to use the `h3arrow` rust library as a optional dependency or `h3ronpy`? I just moved `h3arrow` into the h3ronpy repo and planned to not push it to crates.io anymore, as there are no other users. In case you need it, I can keep publishing it.

I started migrating to arrow 52 and geoarrow 0.3, but got side-tracked during working on this - so I did not finish it. I will try to push it ahead. Thanks for the migration hints 👍

**Comment by kylebarron** [comment]
> Do you want to use the `h3arrow` rust library as a optional dependency or `h3ronpy`?

Sorry I wasn't clear. Ideally I'd use `h3ronpy` and not make my own Python bindings (lonboard doesn't use Rust itself, only via dependencies, and thus doesn't have a build system in place).
