### ISSUE TITLE
New release with pyarrow dependency removed

### ISSUE THREAD

**Issue by zacdezgeo** [nmandery/h3ronpy#69]
I'm using `h3ronpy` in a project where we are deploying with Lambda. The recent work in #64 enabled us to deploy to lambda, but we had to use specific pre-built wheels. There's a component of our project where users run ingestion workflows on their machines and systems that don't match the wheels we pre-built. 

I looked at the contributing docs, and there wasn't any information about the release cycle. Do you have some process in place? Is there anything I could help with?

**Comment by nmandery** [comment]
Hi - sorry for the delay - I said I wanted to release last week, but did not get around to do so. I just want to merge #70, then I will put this on PyPi

**Comment by kylebarron** [comment]
#73 should unblock #70. Let me know if there's anything else I can do to help the release 🙏

**Comment by nmandery** [comment]
v0.22.0 is now on PyPI :wink:
